import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export const dynamic = 'force-dynamic';

function normalizeContainer(value: unknown) { const number = Number(value); if (!Number.isInteger(number) || number < 0 || number > 299) throw new Error('Le numéro de contenant doit être compris entre 000 et 299'); return number; }
function containerToken(reference: string, numero: number) { const safeReference = reference.replace(/[^A-Za-z0-9_-]/g, '').slice(0, 32) || 'CONTENANT'; return `CNT-${safeReference}-${String(numero).padStart(3, '0')}-${Math.random().toString(36).slice(2, 10)}`; }
function serialize(archive: any) { return { ...archive, dateExpedition: archive.dateExpedition.toISOString(), createdAt: archive.createdAt.toISOString(), updatedAt: archive.updatedAt.toISOString(), lignes: archive.lignes.map((line: any) => ({ ...line, dateExpedition: line.dateExpedition.toISOString(), createdAt: line.createdAt.toISOString() })), contenants: archive.contenants.map((container: any) => ({ ...container, createdAt: container.createdAt.toISOString(), qrPath: `/contenant/${encodeURIComponent(container.qrToken)}` })) }; }
export async function GET() { try { const archives = await prisma.expeditionArchive.findMany({ include: { lignes: { orderBy: { createdAt: 'asc' } }, contenants: { orderBy: [{ reference: 'asc' }, { numero: 'asc' }] } }, orderBy: { dateExpedition: 'desc' } }); return NextResponse.json(archives.map(serialize)); } catch (error: any) { return NextResponse.json({ error: error.message }, { status: 500 }); } }
export async function POST(request: NextRequest) { try { const data = await request.json(); if (!data.blId || !data.blNumero || !data.client) return NextResponse.json({ error: 'BL, client et numéro de BL sont requis' }, { status: 400 }); const dateExpedition = new Date(data.dateExpedition || new Date()); if (Number.isNaN(dateExpedition.getTime())) return NextResponse.json({ error: 'Date d’expédition invalide' }, { status: 400 }); const lignes = Array.isArray(data.lignes) ? data.lignes : []; const contenantsInput = Array.isArray(data.contenants) ? data.contenants : []; if (lignes.length === 0 || contenantsInput.length === 0) return NextResponse.json({ error: 'Ajoutez au moins une ligne et un contenant' }, { status: 400 }); const contenants = contenantsInput.map((item: any) => { const reference = String(item.reference || '').trim(); if (!reference) throw new Error('La référence du contenant est requise'); const numero = normalizeContainer(item.numero); return { reference, numero, qrToken: containerToken(reference, numero), qteEtiquette: Number(item.qteEtiquette) || 0, numeroLot: item.numeroLot ? String(item.numeroLot).trim() : null }; }); const archive = await prisma.$transaction(async (tx) => { const current = await tx.expeditionArchive.upsert({ where: { blId: String(data.blId) }, create: { blId: String(data.blId), client: String(data.client), blNumero: String(data.blNumero), dateExpedition, qteTotalBL: Number(data.qteTotalBL) || 0 }, update: { client: String(data.client), blNumero: String(data.blNumero), dateExpedition, qteTotalBL: Number(data.qteTotalBL) || 0 } }); await tx.expeditionArchiveLigne.deleteMany({ where: { expeditionId: current.id } }); await tx.expeditionContenant.deleteMany({ where: { expeditionId: current.id } }); await tx.expeditionArchiveLigne.createMany({ data: lignes.map((line: any) => ({ expeditionId: current.id, client: String(data.client), refProduit: String(line.refProduit || '-'), designation: String(line.designation || '-'), blNumero: String(data.blNumero), dateExpedition, qteEtiquette: Number(line.qteEtiquette) || 0, numeroContenant: String(line.numeroContenant || '000').padStart(3, '0'), numeroLot: line.numeroLot ? String(line.numeroLot).trim() : null, qteTotalBL: Number(line.qteTotalBL) || Number(data.qteTotalBL) || 0 })) }); await tx.expeditionContenant.createMany({ data: contenants.map((item: any) => ({ ...item, expeditionId: current.id })) }); return tx.expeditionArchive.findUnique({ where: { id: current.id }, include: { lignes: true, contenants: true } }); }); return NextResponse.json(serialize(archive), { status: 201 }); } catch (error: any) { return NextResponse.json({ error: error.message || 'Impossible d’enregistrer l’expédition' }, { status: 400 }); } }
